all: nodejs-components.png trireme-components.png

nodejs-components.png: nodejs-components.dot
	tred nodejs-components.dot | dot -Tpng > nodejs-components.png

trireme-components.png: trireme-components.dot
	tred trireme-components.dot | dot -Tpng > trireme-components.png
	
